/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreen;

import javax.swing.JOptionPane;

/**
 *
 * @author Desy
 */
public class SplashScreenku extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreenku
     */
    public SplashScreenku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BrainTeaster = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        LogoGambar = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();
        LoadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1300, 900));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BrainTeaster.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BrainTeaster.setForeground(new java.awt.Color(51, 102, 255));
        BrainTeaster.setText("Brain Teaster Quiz");
        Background.add(BrainTeaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 520, -1));

        LoadingValue.setText(" 0%");
        Background.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, -1, 30));

        LogoGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreen/Assets/otak3.jpg"))); // NOI18N
        LogoGambar.setText("jLabel1");
        Background.add(LogoGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1090, 600));

        LoadingBar.setForeground(new java.awt.Color(255, 102, 204));
        Background.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 1310, 20));

        LoadingLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LoadingLabel.setText("Loading...");
        Background.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, 20));

        jLabel1.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        jLabel1.setText("Created by Desi Nurfitriani");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 210, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreenku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreenku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreenku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreenku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    SplashScreenku sp =new SplashScreenku();
    sp.setVisible(true);
    
    try{
         for(int i= 0;i<=100;i++){
        Thread.sleep(25);
        sp.LoadingValue.setText( i + "%");
        if (i==10){
        sp.LoadingLabel.setText("Masih 10 %...");}
        
        if (i==20){
        sp.LoadingLabel.setText("Udah 20 %...");}
        
        if (i==50){
        sp.LoadingLabel.setText("Udah Setengah persen...");}
        
        if (i==70){
        sp.LoadingLabel.setText("Dikit lagi !...");}
        
        if (i==80){ 
        sp.LoadingLabel.setText("Monggo Sami Mampir!...");}
        
        sp.LoadingBar.setValue(i);
    } 
    }catch (Exception e){
   JOptionPane.showMessageDialog(null, e);
    }
     Beranda Bd=new Beranda();//Membuat Instant dari kelas Beranda
            Bd.setVisible(true);//Menampilkan kelas beranda
         //   this.dispose();//Menutup kelas Login
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BrainTeaster;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel LogoGambar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
